# Generated by Django 3.2.3 on 2021-05-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker_symbol', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=5000)),
                ('current_price_usd', models.DecimalField(decimal_places=10, max_digits=20)),
                ('market_cap', models.TextField(max_length=50)),
            ],
        ),
    ]
