# Generated by Django 3.2.3 on 2021-05-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='market_cap',
            field=models.CharField(max_length=50),
        ),
    ]
