# Generated by Django 3.2.3 on 2021-05-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_cryptocurrency_market_cap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='market_cap',
            new_name='market_cap_usd',
        ),
    ]
