# Generated by Django 3.2.3 on 2021-05-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_historicaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='exchanges',
            field=models.ManyToManyField(blank=True, to='main_app.Exchange'),
        ),
    ]
